//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBL { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaThuCung { get; set; }
        public Nullable<int> MaPhuKien { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhuKien PhuKien { get; set; }
        public virtual ThuCung ThuCung { get; set; }
    }
}
