//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatLich
    {
        public int MaDatLich { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string HoTenKhach { get; set; }
        public string SDTKhach { get; set; }
        public Nullable<System.DateTime> NgayHen { get; set; }
        public string GhiChu { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
