//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public int MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
        public string Hinh { get; set; }
    
        public virtual LoaiDichVu LoaiDichVu { get; set; }
    }
}
