//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int MaKM { get; set; }
        public string TenKhuyenMai { get; set; }
        public string CodeKM { get; set; }
        public Nullable<int> PhanTramGiam { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string MoTa { get; set; }
        public string HinhKM { get; set; }
    }
}
