//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHOPBANTHUCUNGEntities : DbContext
    {
        public SHOPBANTHUCUNGEntities()
            : base("name=SHOPBANTHUCUNGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANNER> BANNERs { get; set; }
        public virtual DbSet<BANNERCHINH> BANNERCHINHs { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<ChamSocSucKhoe> ChamSocSucKhoes { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<DatLich> DatLiches { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DichVuChamSocSucKhoe> DichVuChamSocSucKhoes { get; set; }
        public virtual DbSet<HinhAnhPhu> HinhAnhPhus { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LoaiDichVu> LoaiDichVus { get; set; }
        public virtual DbSet<LoaiPhuKien> LoaiPhuKiens { get; set; }
        public virtual DbSet<LoaiThuCung> LoaiThuCungs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhuKien> PhuKiens { get; set; }
        public virtual DbSet<QuanLy> QuanLies { get; set; }
        public virtual DbSet<ThuCung> ThuCungs { get; set; }
        public virtual DbSet<TinhTrang> TinhTrangs { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
    }
}
