//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhuKien()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.HinhAnhPhus = new HashSet<HinhAnhPhu>();
        }
    
        public int MaPhuKien { get; set; }
        public string TenPhuKien { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
        public string Hinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhPhu> HinhAnhPhus { get; set; }
        public virtual LoaiPhuKien LoaiPhuKien { get; set; }
    }
}
